# Generated by Django 2.2.11 on 2020-03-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0002_user_is_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='answer1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='answer2',
            field=models.TextField(),
        ),
    ]
